//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgcustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lgcustomer()
        {
            this.lginvoices = new HashSet<lginvoice>();
        }
    
        public decimal cust_code { get; set; }
        public string cust_fname { get; set; }
        public string cust_lname { get; set; }
        public string cust_street { get; set; }
        public string cust_city { get; set; }
        public string cust_state { get; set; }
        public string cust_zip { get; set; }
        public Nullable<decimal> cust_balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lginvoice> lginvoices { get; set; }
    }
}
