//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgemployee
    {
        public decimal emp_num { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_email { get; set; }
        public string emp_phone { get; set; }
        public System.DateTime emp_hireDATETIME { get; set; }
        public string emp_title { get; set; }
        public Nullable<decimal> emp_comm { get; set; }
        public Nullable<decimal> dept_num { get; set; }
    }
}
