//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lginvoice
    {
        public decimal inv_num { get; set; }
        public Nullable<System.DateTime> inv_DATETIME { get; set; }
        public Nullable<decimal> cust_code { get; set; }
        public Nullable<decimal> inv_total { get; set; }
        public Nullable<decimal> employee_id { get; set; }
    }
}
