//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgline
    {
        public decimal inv_num { get; set; }
        public decimal line_num { get; set; }
        public string prod_sku { get; set; }
        public Nullable<decimal> line_qty { get; set; }
        public Nullable<decimal> line_price { get; set; }
    }
}
