//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgproduct
    {
        public string prod_sku { get; set; }
        public string prod_descript { get; set; }
        public string prod_type { get; set; }
        public string prod_base { get; set; }
        public string prod_category { get; set; }
        public Nullable<decimal> prod_price { get; set; }
        public Nullable<decimal> prod_qoh { get; set; }
        public Nullable<decimal> prod_min { get; set; }
        public Nullable<decimal> brand_id { get; set; }
    }
}
