//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u17112631_A2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgvendor
    {
        public decimal vend_id { get; set; }
        public string vend_name { get; set; }
        public string vend_street { get; set; }
        public string vend_city { get; set; }
        public string vend_state { get; set; }
        public string vend_zip { get; set; }
    }
}
